services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=miniai
      - POSTGRES_PASSWORD=miniai@123
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - db:/data/postgres
    ports:
      - '5431:5432'
    networks:
      - shared_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-miniai} -d ${DB_NAME:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: rag-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  db:
